errbit/errbit

app/assets/stylesheets/errbit.css.erb

On error list page, comments with especially long words (typically :
urls) break layout.
Fixed it by using the same forced width and wrapping settings than on
error message.

FIX inline comments styles

---

Gemfile.lock

This bumps some gem version for ruby 2.2 support:
htmlentities: duplicate hash key
kgio/raindrops: compilation error due to rubysig.h deprecation

Ruby 2.2 compatibility

---

app/helpers/problems_helper.rb
spec/helpers/problems_helper_spec.rb

Without this change, the truncated text, which is already html escaped gets escaped again in the map block.

Fix double escaping of problem title in list view

---

Gemfile
Gemfile.lock
Procfile.dev

It would be better to use same app server between dev and prod.
Is there any reason to use puma on dev?

Remove puma and Procfile.dev

---

.gitignore
Capfile
Gemfile
Gemfile.lock
config/config.example.yml
config/deploy.example.rb
config/deploy/production.example.rb
docs/deployment/capistrano.md

- No more deployment section in `config.yml`. Now need to customize `deploy.rb` and `production.rb`.
- `errbit:setup_config` does not create secret_token.rb
- added capistrano-rbenv: enabled when `rbenv` env variable is set when running capistrano. (e.g. `rbenv=1 bundle exec cap production deploy:check`)

capistrano 3

---

app/models/notification_services/gtalk_service.rb
spec/models/notification_service/gtalk_service_spec.rb

The GoogleTalk/Jabber Notification Service was leaking keepalive threads, because xmpp4r creates an internal keealive thread on connect that is only cleaned up when closing the client.
This lead to workers quickly running out of threads and throwing exceptions like `ThreadError: can't alloc thread`. The fix ensures that the xmpp4r client is always closed after notifications have been sent.
Example Exception-Backtrace:
```
ThreadError: can't alloc thread:
xmpp4r-0.5.5/lib/xmpp4r/connection.rb:83→ new
xmpp4r-0.5.5/lib/xmpp4r/connection.rb:83→ connect
xmpp4r-0.5.5/lib/xmpp4r/client.rb:71→ connect
app/models/notification_services/gtalk_service.rb:45→ create_notification
mongoid-4.0.0/lib/mongoid/relations/proxy.rb:150→ method_missing
app/models/notice.rb:196→ services_notification
```

Fix GtalkService Keeaplive-Thread leak

---

Gemfile
Gemfile.lock

This PR adds the rails_12factor gem to the Gemfile, but it is only required if the `HEROKU` environment variable is set. This should have no ill effect on other deployment targets. This should solve issue #806…

Adds the rails_12factor gem for Heroku

---

Gemfile

It seems errbit officially supports [Ruby 2.1 or higher](https://github.com/errbit/errbit#requirements).
Otherwise Heroku uses Ruby 2.0.0 when `Gemfile` has no `ruby` section.
So I specify `ruby` section for Heroku.

Allow to specify Ruby version in Gemfile

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/api/v1/notices_controller.rb
app/controllers/api/v1/problems_controller.rb
app/controllers/api/v1/stats_controller.rb
config/boot.rb

Not sure if we want to add this or support it, but this change seems to allow you to run errbit under jruby-9000. It might be nice to have, even if we don't fully support it. Any thoughts?

add experimental support for jruby-9000-dev

---

config/deploy.example.rb

[This change](427ab3b0a0f9a03c60bb019dc1be28793a284bc4) is really great and is a huge simplification of the deployment/configuration process.
Although, the `config/deploy.example.rb` still mention the copy and linking of `config.yml` and `mongoid.yml`
I've removed them in my `config/deploy.rb` and it works.

Don't link and copy old config files

---

app/controllers/users/omniauth_callbacks_controller.rb

The user's organization ids are converted to String, but the configuration value `Errbit::Config.github_org_id` is always an Integer. They can't possibly match.
Unifying value types make this work.

github_org_id can't match (String vs. Integer)

---

app/controllers/problems_controller.rb
app/helpers/hash_helper.rb
app/views/issue_trackers/issue.md.erb
app/views/issue_trackers/issue.txt.erb
spec/views/issue_trackers/issue.md.erb_spec.rb
spec/views/issue_trackers/issue.txt.erb_spec.rb

This PR adds an unused txt format issue tracker body and a markdown format issue tracker body to prepare for issue trackers that can specify which template to use.

Refs #785 add md and txt issue tracker templates

---

app/controllers/problems_controller.rb
app/models/issue.rb
spec/controllers/problems_controller_spec.rb
spec/models/issue_spec.rb

For #783: Allow issue trackers to implement their own titles and bodies while preserving sane defaults

783 allow custom issue tracker templates

---

Gemfile
Gemfile.lock

[foreman](https://github.com/ddollar/foreman) says it should not be in Gemfile
> Ruby users should take care not to install foreman in their project's Gemfile.

remove foreman

---

Gemfile
Gemfile.lock

[dotenv-deployment](https://github.com/bkeepers/dotenv-deployment) is deprecated.
> This gem is deprecated and no longer maintained. Use dotenv-rails, or manually configure dotenv to meet your own needs.
Tested on my installation.

use dotenv-rails

---

app/models/notification_services/slack_service.rb

https://github.com/errbit/errbit/commit/28e1148fd14c63b757bbdf7824fc174d236f49d2 changed SlackService notifier to rely only on the service_url, and no longer needing an api_token
This apparently broke the form for any newly created app, because a notifier was only considered `configured?` if the api_token was set, which is now impossible to do for slack
I wasn't really sure how to go about this, because I'm not very familiar with the codebase yet, but I just thought I'd push the fix I've made on my fork so this can be properly discussed

Fixing slack integration

---

app/controllers/problems_controller.rb
app/views/mailer/comment_notification.html.haml
app/views/mailer/comment_notification.text.erb
app/views/mailer/err_notification.html.haml
app/views/mailer/err_notification.text.erb
config/locales/en.yml
spec/controllers/problems_controller_spec.rb
spec/mailers/mailer_spec.rb
spec/views/apps/show.html.haml_spec.rb

"Error(s)" and "Err(s)" where mixed up in the translations.

Be consistent by always using error(s).

---

Gemfile
README.md

Here's my attempt at documenting the method for creating and/or installing issue tracker plugins. I removed most of the docs for configuring the individual issue trackers because firstly, I know that they're out of date and don't actually work with current versions of errbit, but secondly because those docs belong in the individual plugin repos.
Keep in mind this pattern is the blueprint for what we want to happen next for notification integrations as plugins. If there's anything we don't like, we should try to spot it now.

#782 add docs for installing tracker plugins

---

config/deploy.example.rb

Unicorn uses shared/tmp/pids instead of shared/pids

errbit:setup creates tmp/pids

---

app/views/layouts/mailer.html.haml

This fixes issue #886 by using the correct fingerprinted logo asset.

Use asset pipeline logo in notifications

---

Gemfile.lock
app/models/notification_services/hipchat_service.rb
db/migrate/20150527202629_add_v1_to_hipchat_notification_services.rb
spec/fabricators/notification_service_fabricator.rb
spec/models/notification_service/hipchat_service_spec.rb

HipChat has a [new API](https://www.hipchat.com/docs/apiv2) for a while now, and the new API allows users to use their own API token instead of requiring an administrator to generate one for them. V2 is also the only available API version for people running their own HipChat server.
This PR updates the HipChat gem, uses a migration to set already configured HipChat notifications to v1, and allows users to switch to v2 at their own pace.

Support HipChat v2 API

---

Gemfile
Gemfile.lock

Hi. During deployment Errbit I get the following error:
```
INFO [0a491011] Running ~/.rbenv/bin/rbenv exec bundle exec rake assets:precompile as deploy@server.dev
DEBUG [0a491011] Command: cd /home/deploy/errbit/releases/20150529161719 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.2 RAILS_ENV=production ~/.rbenv/bin/rbenv exec bundle exec rake assets:precompile )
DEBUG [0a491011]        rake aborted!
DEBUG [0a491011]        ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
DEBUG [0a491011]        /home/deploy/errbit/shared/bundle/ruby/2.2.0/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect'
DEBUG [0a491011]        /home/deploy/errbit/shared/bundle/ruby/2.2.0/gems/execjs-2.0.2/lib/execjs.rb:5:i …
```

Fix a bug during deploy [assets:precompile]

---

Gemfile
Gemfile.lock

Release notes: http://weblog.rubyonrails.org/2015/6/16/Rails-3-2-22-4-1-11-and-4-2-2-have-been-released-and-more/
Security alerts at https://gemnasium.com/errbit/errbit/alerts

Security update: Rails 4.1.11 release

---

.teatro.yml

This config changes admin's password to `TeatroTeatro` so Teatro can be used again :)

Set special password for using in Teatro

---

app/models/notice.rb
spec/models/notice_spec.rb

This PR fixes a problem when error reports with file URIs are submitted.
E.g. in cases where reports are submitted from our Cordova apps and
request['url'] = "file:///path/to/some/resource"
then
URI.parse(request['url']).host == nil
However, `Notice#host` is expected to always return a string (a hostname or "N/A"). When "file:///..." URIs are used `Notice#host` is returning nil and breaking Errbit code (e.g. in app/models/problem.rb#85). This PR fixes that.
Note, I've simplified the fix to the following code:
uri && uri.host || "N/A"
but it could also be written as 
(uri.blank? or uri.host.blank?) ? "N/A" : uri.host
in keeping with the original form. Up to you.
New test added and all tests passing.

Fixed notice parsing error when request['url'] is 'file:///...'

---

app.json

Ruby 2.2.3 is the latest release of Ruby.

Use Ruby 2.2.3 by default for Heroku deployment

---

app/decorators/backtrace_line_decorator.rb

Bitbucket has a new url schema for linking to files that is slightly more verbose and allows for selection of ranges. 
This simple restores previous behavior. 
See https://bitbucket.org/site/master/issues/10622/url-link-to-multiple-lines-with-cl-xx-yy

Fix bitbucket link to bitbucket source.

---

app/models/error_report.rb
app/models/notice.rb
db/migrate/20150926035420_cache_app_on_notice.rb
spec/fabricators/err_fabricator.rb

Notices always have an app API key when they arrive at Errbit, so it
makes sense to cache the app id onto the notice object. This will allow
for more efficient refingerprinting and reporting down the road.

cache app on notice

---

config/routes.rb

https://github.com/errbit/errbit/commit/6a233224beeb6f7882f488cbfc41a2858f8f00bb#diff-21497849d8f00507c9c8dcaf6288b136L63
This commit changes errbit json api endoint, but Airbrake's json api is yet `notices` not `create-notice`.
so, it is necessary to accept old(?) api endpoint of Airbrake.

Add airbrake json api url routing

---

Gemfile

Some users are reporting errors due to incompatible ruby versions. This
commit aims to provide users with a helpful error message so they can
more easily spot the issue.

incompatible ruby version error

---

.rspec
spec/models/notification_service/notification_service_spec.rb

This is usually a good way to ferret out state leaking from one test to another, making the tests frustrating to work with. Fortunately it seems like everything is in pretty good order. 
I've been running this in a console locally for a while:
```
while (true) { bundle exec rspec --order random || say "failed once" }
```
Looks good so far. 
If this passes on Travis I'll push an update to use a random test ordering each time, and not a fixed seed like now.

RSpec: run in random order

---

Gemfile
Gemfile.lock

The Test::Unit runner will attempt to parse options that are meant for RSpec. See https://github.com/rspec/rspec-rails/issues/1343 for details.
This makes `bundle exec rake` work.

Remove test-unit to avoid 'invalid option' message

---

db/migrate/201510290041_extract_issue_tracker.rb

Addresses #926.
Between 0.4.0 and 0.5.0 all old migrations were removed because they were assumed to have been run in any production environment. However, it appears that the data migration for the IssueTrackers collection was [changed](https://github.com/errbit/errbit/commit/8dbfda4566fbf24b73f6173967fb0d0de032d296) during the process of building 0.4.0. Which meant anyone before then would not have the new structure in place. The proposed solution of migrating to 0.4.0 and then migrating forwards does not work if the MongoDB database underlying errbit was already moved to MongoDB 3.0 (which MongoLabs did for all their databases), because 0.4.0 doesn't have the updated Mongoid 5 drivers needed to connect.
This restores the commit so that it errbit installations before 0.4.0 can be …

Restore migration to extract issue trackers

---

app/views/apps/show.html.haml
app/views/problems/index.html.haml
spec/views/problems/index.html.haml_spec.rb

Fixed bug:
1. Go to errors page /problems
2. Title = Unresolved Errors, button = show resolved
3. Click show resolved button (link actually)
4. Title has the same name instead of 'All Errors' and button is the same as before. So now we can't hide resolved errors
Problem was in using instance variable inside view.

fixed button 'show/hide resolved' on errors#index page

---

app/models/notice.rb
app/models/problem.rb
spec/models/notice_spec.rb
spec/models/user_spec.rb

Long messages need to be truncated so that Errbit will not try to cache
messages that are too long on Problem records because the mongo text
index will complain if the text is too long. Also, it's a good idea to
have these kinds of limits in general.

Refs #1001 truncate long messages on cache

---

app/controllers/apps_controller.rb
spec/controllers/apps_controller_spec.rb

Prior to this change, the `#sort` method was being handled by Mongoid and sent
to MongoDB, resulting in the `App#<=>` method being ignored for this purpose.
See additional discussion in #973

Ensure that App#<=> is used for sorting

---

app/assets/stylesheets/errbit.css.erb
app/helpers/problems_helper.rb
app/views/problems/_table.html.haml
spec/helpers/problems_helper_spec.rb

Long names in the problems index can blow up the table layout, causing
ugliness and potentially horizontal scrolling. This change adds
whitespace: nowrap and sets a few td widths to keep the layout from
jumping around.

Refs #1011 problems index layout fix

---

app/models/problem.rb
spec/models/problem_spec.rb

Configuring a protocol did not use that protocol when generating the URL, such as when used in the Slack integration.

Make Problem#url use the configured protocol

---

lib/airbrake_api/v3/notice_parser.rb
spec/fixtures/api_v3_request_with_deprecated_user_keys.json
spec/lib/airbrake_api/v3/notice_parser_spec.rb

The airbrake gem v5 has changed the keys for the user payload as described in #1026.

Add support for new user payload

---

app/controllers/api/v3/notices_controller.rb
spec/controllers/api/v3/notices_controller_spec.rb

When using the airbrake-ruby gem (used by airbrake 5.0), the client throws an error due to a bad return code from the v3 api controller.
The expected return code is 201 created, but currently the errbit controller returns 200 ok.
See: https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/response.rb#L22

Airbrake 5.0 expects 201 status code for v3 api

---

app/controllers/apps_controller.rb

Checking for `.present?` on the NotificationService class or it's subclasses always returns false.  Using a not `.nil?` check solves the issue.

fixes #1040

---

app/controllers/apps_controller.rb

Uses flash.now instead of just flash when rendering and not redirecting.

closes #1053 don't carry forward flash notices

---

app/models/notification_services/slack_service.rb
spec/fabricators/notice_fabricator.rb
spec/models/notification_service/slack_service_spec.rb

Before:
After:
This also includes #1023.
I removed "Last noticed at", as this should be around the same time when the notification comes.
At least in ruby `error_class` (FooError) is always prefixed in the `message` (FooError: Too much bar). Also problems#index shows only the message.

More compact slack notifications

---

lib/airbrake_api/v3/notice_parser.rb
spec/lib/airbrake_api/v3/notice_parser_spec.rb

According to the [API V3 docs](http://airbrake.io/docs/#create-notice-v3) context has a separate key for _hostname_.
When I have 2 app servers: `app01.infra.example.com` and `app02.infra.example.com`  those handle similar requests, I want to realize which one produces the error.
In this case parsing the URL doesn't make sense.

Get hostname from the hostname key

---

.env.default
Gemfile
Gemfile.lock
README.md
app/assets/stylesheets/errbit.css.erb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/sessions/new.html.haml
app/views/shared/_link_google_account.html.haml
app/views/users/edit.html.haml
app/views/users/show.html.haml
config/initializers/devise.rb
config/load.rb
config/routes.rb
docs/configuration.md
spec/acceptance/acceptance_helper.rb
spec/acceptance/sign_in_with_google_spec.rb

I was implemented authentication by google to errbit.
The reason for this is that, GitHub is offen unusable.
In the authentication by Google, such a situation is considered unlikely to occur.
Implementation is the following three points.
- Authentication by google
- Test of authentication by google
- Update of the document
Please tell me if there is a correction point:dog:

Add omniauth by google

---

docs/deployment/capistrano.md

Please correct me if I'm wrong but first the config files should be uploaded to the destination server and later check the configs.
If I run first `bundle exec cap production deploy:check` I'll get this error:
```
ERROR linked file /var/www/apps/errbit/shared/config/puma.rb does not exist on 
(Backtrace restricted to imported tasks)
```
Running first `bundle exec cap production errbit:setup` will pass

First setup the config files and later check

---

README.md

According to [configuration page](https://github.com/errbit/errbit/blob/master/docs/configuration.md) params has name with `ERRBIT_` prefix

Update LDAP documentation

---

app/views/apps/_configuration_instructions.html.haml

refs #1102 
fix docs for airbrake 5.4
https://github.com/airbrake/airbrake-ruby/blob/989187744e7ea65f3383aacbac0e0f27500ce62a/lib/airbrake-ruby/config.rb#L133
In 5.4, an exception occurs at the point of the case `to_i` project_id is true.
project_id was work in -1, but it is first aid.

fix does not work with airbrake 5.4 refs #1102

---

app/views/apps/_configuration_instructions.html.haml

closes #1106 
airbrake 5.4 gem does not set environment if not configured in initializer.
as suggested in #1106 this change adds additional comments to the configuration instructions

add instructions to configure environment in errbit initializer

---

Gemfile.lock

The old libv wasn't compiling.
It was getting this error:
```
Installing libv8 3.16.14.13 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /Users/andrei/.rvm/gems/ruby-2.3.1/gems/libv8-3.16.14.13/ext/libv8
/Users/andrei/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20160727-65116-eqmldx.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.10
Using compiler: /usr/bin/c++ (clang version 7.3.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/andrei/.rvm/gems/ruby-2.3.1/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from …
```

libv8 updated to 3.16.14.15 to be able to compile it on OS X

---

app/views/devise/sessions/new.html.haml

If you disable Google authentication, the `/users/sign_in` page throws an exception of type: `ActionController::UrlGenerationError`

Fix UrlGenerationError exception thrown when Google auth is disabled

---

Gemfile
Gemfile.lock

When i run rspec spec the acceptance tests are failing with the following error message:
_Cliver::Dependency::NotFound:
Could not find an executable ["phantomjs"] on your path._
I had to add phantomjs to the Gemfile [as described here](https://github.com/colszowka/phantomjs-gem#usage-with-poltergeistcapybara)

add phantomjs gem to fix failing acceptance tests

---

docs/deployment/heroku.md

I ran through the Heroku installer and didn't have an admin user. I had to bootstrap to set it up.
This is lower in the page, but it wasn't clear where the manual instructions ended.  We could say "finish configuration (link)" instead of this if you think that's better.

Remind heroku button users to bootstrap

---

docs/deployment.md

This is a pull request in response to #1137 .
I haven't created a separate docker image or changed the docker documentation.
-----------------
The section could potentially be broken out into a subpage.
I wanted to link to a blog or article about using a reverse-proxy to
wrap a app-server with HTTPS. Unfortunately, I couldn't find an example
that explained both reverse-proxying and TLS.

Document how errbit can be served on HTTPS

---

.travis.yml

"2.2" means "2.2.0" on Travis CI.
ref: https://travis-ci.org/errbit/errbit/jobs/181392638
And it is too older to break build.

Update Ruby from 2.2 to 2.2.6

---

app/models/notification_services/slack_service.rb
spec/models/notification_service/slack_service_spec.rb

* closes https://github.com/errbit/errbit/issues/1136
* see https://github.com/mattermost/platform/issues/3666#issuecomment-238098539
a really small change, that should enable [Mattermost](https://github.com/mattermost/platform) as Slack alternative.
i used the curl example to check if Slack has a problem with "Times Occured" as a String
```
curl -d '{"username":"Errbit","icon_url":"https://raw.githubusercontent.com/errbit/errbit/master/docs/notifications/slack/errbit.png","attachments":[{"fallback":"[Klaus][development][welcome#index]: RuntimeError http://errbit.example.com/apps/5795cbebdf0f1d0009000000/problems/5795cffadf0f1d0017000007","title":"Hugo","title_link":"http://errbit.example.com/apps/5795cbebdf0f1d0009000000/problems/5795cffadf0f1d0017000007","text":"welcome#index","color":"# …
```

change slack notification service to be mattermost compatible

---

docker-compose.yml

MongoDB 3.2 defaults to WiredTiger as storage engine. As with WiredTiger MongDB finally supports compression the resulting database in many cases has a far smaller file size.
If the mongo:3.2 container is started with an existing volume created by the old 3.0 version the old storage engine is automatically used, therefor this change should be downward compatible.

Default to using MongoDB with compression

---

config/initializers/action_mailer.rb
config/load.rb
docs/configuration.md
spec/initializers/action_mailer_spec.rb

- smtp_enable_starttls_auto, smtp_openssl_verify_mode
I did not see a way to have a default value for these settings.  I would like to ensure that "enable_starttls_auto" as the expected default value of `true`.
See: http://api.rubyonrails.org/classes/ActionMailer/Base.html#class-ActionMailer::Base-label-Configuration+options

smtp config: support additional ssl related keys

---

README.md

When I followed the current link to Github I couldn't find the button to register a new app.
So I think a more specific link would avoid needing to Google it.

Update README link to Github app registration

---

app/models/notification_services/slack_service.rb
app/views/apps/_service_notification_fields.html.haml
spec/fabricators/notification_service_fabricator.rb
spec/models/notification_service/slack_service_spec.rb

This is a follow up PR to #1095.
This adds the ability to users to select a channel in which the Slack notifications will be send when setting up Slack notifications.
The channel field is not compulsory and, if empty, the default channel setup on slack when creating the webhook.

Slack channels

---

docs/deployment/dokku.md

Hi,
First, I've to thank your for this great project.
My issue is that installing Errbit on dokku fails because it uses the `Dockerfile` as the deployment method instead of the ordinary Buildpack way.
As an example of the deployment output, I've added the error messages:
```
...
curl: (7) Failed to connect to 172.17.0.3 port 8080: Connection refused
!     Check attempt 5/5 failed.
=====> errbit web container output:
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
Bundler::VersionConflict: Bundler could not find compatible versions for gem "ffi":
In snapshot (Gemfile.lock):
ffi (= 1.9.8) java
In Gemfile:
launchy was resolved to 2.4.3, which depends on
spoon (~> 0.0.1) java was resolved to 0.0.4, which depends on
ffi java
launchy was resolved to 2.4.3, which depends on …
```

Document the necessity to avoid the Dockerfile deployment detection

---

Dockerfile

Ordering of commands is important in the Dockerfile because when asset:precompile is run, it's done as root, which then creates the /app/tmp file with root permissions. 
Subsequently, after the docker image is started, when connecting to the website for the first time you get a Permission denied error from Devise like this:
This relates to the recent changes from #1160

Fix tmp directory permissions in Dockerfile

---

app/models/notice_fingerprinter.rb
spec/models/notice_fingerprinter_spec.rb

Sometimes it's nil
Due to storage limit (especially on Heroku)

Fix notice fingerprinter when backtrace is nil

---

app/assets/stylesheets/errbit.css.erb

Right now, some of the main navigational buttons are deceptively clickable. I kept finding myself clicking multiple times on the edges of buttons with nothing happening and thinking something wasn't working. It was only because the links have wrapping elements that produce the boundary, which the links don't fully expand across vertically. 
Here's some before/after screens of the css diff: 
| | Main Nav | Action Buttons | Session Nav |
| ----- | ----- | ----- | ----- |
| Before | ![before](https://cl.ly/3L3Z0I3I0P0w/Screen%20Shot%202017-03-07%20at%208.26.14%20PM.png) | ![before](https://cl.ly/0v3R1G2Q0w1Y/Screen%20Shot%202017-03-07%20at%208.27.24%20PM.png) | ![before](https://cl.ly/3G3F3U2R1b44/Screen%20Shot%202017-03-07%20at%208.29.11%20PM.png) |
| After | …

Expand Clickable Area on Buttons

---

config/locales/en.yml

Translates submit button on /users/new page to english
See #1168

fix missing english translation

---

README.md

Previously the README had two of four product screenshots return 404, now using the images on https://errbit.com

README: fix the prominent screenshot links

---

app/models/error_report.rb
docs/configuration.md
spec/models/error_report_spec.rb

This makes the behaviour of `ERRBIT_EMAIL_AT_NOTICES` consistent with that of `ERRBIT_NOTIFY_AT_NOTICES`.
We work hard to keep the exception notifications in our apps to zero. The default configuration is to only send emails for the 1st, 10th and 100th occurrence of an error. We've found that this sometimes means we mark the 1st occurrence error as resolved and then it recurs a few more times and we are not notified. We'd prefer to be notified every time, hence this change.

Allow sending email notification for *every* error

---

app/models/notification_service.rb
app/models/notification_services/hipchat_service.rb

When notifications are sent to hipchat rooms, developers can't receive a push notification unless they are @mentioned.  Getting a push notification when an error happens seems like a fairly useful feature: it definitely is for my team.  I've updated the hipchat notification service to include an @mentioned field that will be prepended to the error message so all users @mentioned can receive the push notification.
One caveat about hipchat though, is that their API only allows @mentions when the message format is 'text'.  The default format (and the one currently used by errbit) is 'html'.  So for this pull request, if @mentions is set the notification service will use the 'text' format, otherwise it will keep the original 'html' format.

support mentioning users as part of hipchat room notification

---

app/assets/stylesheets/errbit.css.erb
app/views/problems/_table.html.haml

Ever since we started allowing tables to have varying numbers of columns, we've had problems with our static layout. There are a number of competing goals we have:
1. tables should look fine even when there's lots of non-breaking characters in each of the text fields
2. when text is too long, it should `overflow: ellipsis`
3. when text is too long, it should have a title tag with (more) complete text on hover
4. when text is too long, we should avoid excessively tall table cells, refusing to wrap text wherever possible
5. when columns are added/removed via configuration, the table should remain as wide as its container and not blow outside its bounds
6. ideally, the table should still behave like a classic HTML table and adapt dynamically to the size of its contents
This is surprisingly …

allow fluid table columns on problem index

---

config/locales/en.yml

Used to be called "Tenant" in older versions, now it's portuguese, I propose "Origin"?

Fix portuguese word in en.yml

---

app/models/notification_services/webhook_service.rb
spec/models/notification_service/webhook_service_spec.rb

NotificationServices::WebhookService#message_for_webhook
previously returned an Hash with a single key "problem"
with a string as value:
{
"problem": "Stringified json here"
}
actually loosing almost all the "problem" properties.
Now the "problem" key bring on a child Hash as expected.

Fix webhook service notification payload

---

app/assets/stylesheets/errbit.css.erb

For some reason the newline after button text caused the button to
show at double it's normal height.
This fix adds css to prevent line-wrapping in button texts.

Fix whitespace issues for issue tracker buttons

---

app/mailers/mailer.rb

Decorator's association like `ProblemDecorator.new(comment.err).notices.first` doesn't optimise the query, instead it pulls all the `notices` from database. When a `problem` has many `notices`, this becomes a critical performance issue. 
Perhaps no additional test is required.

Improve the notices query in comment notification

---

app/controllers/api/v3/notices_controller.rb
spec/controllers/api/v3/notices_controller_spec.rb

Fixes compatibility issues with javabrake, the new Airbrake java client. 
This client uses the X-Airbrake-Token header instead of sending the apiKey in the ?key=foobar query parameter.

Fix #1225 - Use X-Airbrake-Token header when present

---

Dockerfile

#1232 
As OpenShift assigns an arbritrary user to the container at start up the user requires a read and execute permission to run/read the code, so the permission has been modified accordingly.
700 -> 705

Allowing Errbit to run on OpenShift

---

app/controllers/api/v3/notices_controller.rb
spec/controllers/api/v3/notices_controller_spec.rb

This fixes #1236 where airbrake-ruby 2.5.1 added the Authorization header for the project key instead. 
See airbrake/airbrake-ruby#278

Allow Authorization header for authentication

---

docs/deployment/kubernetes.md

the file is `docs/deployment/example/kubernetes/rc.yml` not `docs/deployment/example/kubernetes/rc.yaml`, etc.

fix yaml extention typo in kubernetes deployment docs

---

app/controllers/health_controller.rb
config/routes.rb
docs/deployment.md
spec/requests/health_controller_spec.rb

Adding health check endpoints. We need this in order to configure load balancers and orchestration tools like kubernetes.

adding health check endpoints. w/ burnettk

---

Gemfile.lock

Changelog shows only a few bugfixes:
https://github.com/plataformatec/devise/blob/a0af72edfdf2328bcc6586f57748c30422f2cabc/CHANGELOG.md

Devise: conservative upgrade from 3.5.5 to 3.5.10

---

app/models/notification_services/slack_service.rb
spec/models/notification_service/slack_service_spec.rb

It's helpful to see a little more information about the error in Slack,
so now the first five lines of the backtrace show up at the bottom of
the notification.
https://content.screencast.com/users/dsandstrom/folders/Jing/media/ef18cfa1-91f8-4b2d-bd9c-28b0228ae6c4/00000293.png
Fixes #1104

Add backtrace to Slack's notification

---

app/interactors/outdated_problem_clearer.rb
lib/tasks/errbit/database.rake
spec/interactors/outdated_problem_clearer_spec.rb

The configuration was probably renamed in the past, but the rake task and service object was not updated

Fix rake errbit:clear_outdated task

---

Dockerfile

If you attach multiple networks to the docker container the `/sbin/ip route | /usr/bin/awk '/src/{print $NF}'` will print something like this:
```
172.18.0.4
172.20.0.3
172.21.0.3
```
And the HEALTHCHECK command will fail with the following:
```
curl: (3) Illegal characters found in URL
```
This fix picks the first IP and uses this for checking if the service is available or not

Fix docker healthcheck for mutiple networks

---

config/application.rb

Any ruby requires that occur in your application will leak with
Pathnames in the $LOAD_PATH in ruby 2.3/2.4. Beyond that, it's faster
to use strings in the load path. Please join this bug and add your
support for a fix:
https://bugs.ruby-lang.org/issues/14372
Same problem found here: https://github.com/lobsters/lobsters/pull/449
and
https://github.com/opf/openproject/pull/6148

Avoid require memory leak with pathnames in load path

---

lib/configurator.rb
spec/lib/configurator_spec.rb

`YAML.parse` for an empty value `''` returns `false` instead of an expected object, thus directly feeding that into `to_ruby` method fails. This handles the case where environment variable is empty.
Fixes #1261

Handle empty environment variables

---

app/controllers/problems_searcher.rb
app/models/problem.rb
app/views/problems/_table.html.haml
config/locales/en.yml
config/locales/pt-BR.yml

this updates pages like /apps/5a78bd63b33eb400a20e88dd, like this.
before:
after:
Sorting by environments (which is implied as a feature by having an "ENV" column) now seems to work.
this table partial in question is used by two actions:
* apps/show
* problems/index
the conditional (which was already being used elsewhere in the same partial) makes it so problems/index continues to be rendered as before (show the app as well as the env).
this feels slightly higher risk than the other two PRs I just filed, but still very low risk, and hopefully it's a pure UX improvement and not at all controversial. but let me know!

do not show app in table when already on an app/show page

---

app/controllers/problems_controller.rb
spec/controllers/problems_controller_spec.rb

when there are no notices attached to problem. new test fails pre-controller-fix.

fix some nilpointer-style exceptions in the view

---

app/assets/stylesheets/errbit.css.erb
app/views/problems/_table.html.haml

does not really affect the look to my untrained eye.
before:
after:
there is no similar easy fix for five-digit numbers. :)

 avoid truncating count where it is a four digit number

---

app/controllers/health_controller.rb
config/routes.rb
spec/requests/health_controller_spec.rb

we have existing checks for errbit clients that actually use the normal "send-a-notice" api, but it's a bit suboptimal that errbit then ends up sending emails and whatnot. this new API provides pretty much the same assurance that the errbit client is configured correctly, but with fewer side effects. working with @jasquat .

add new health api that can be used to test client config, including api_key

---

.gitignore
app/decorators/backtrace_line_decorator.rb
spec/decorators/backtrace_line_decorator_spec.rb

we got this exception:
````
NoMethodError: undefined method `[]' for nil:NilClass
````
with this backtrace:
````
[PROJECT_ROOT]/decorators/backtrace_line_decorator.rb:18→ file
--
[PROJECT_ROOT]/decorators/backtrace_line_decorator.rb:5→ in_app?
[PROJECT_ROOT]/views/mailer/err_notification.html.haml:31→ block in _app_views_mailer_err_notification_html_haml___2324961091592232048_70027270895640
[PROJECT_ROOT]/views/mailer/err_notification.html.haml:30→ each
[PROJECT_ROOT]/views/mailer/err_notification.html.haml:30→ _app_views_mailer_err_notification_html_haml___2324961091592232048_70027270895640
actionview-4.2.9/lib/action_view/template.rb:145→ block in render
activesupport-4.2.9/lib/active_support/notifications.rb:166→ instrument
actionview-4.2.9/lib/action_view/template.rb:333→ instrument …
```

avoid 500 error when backtrace object is nil

---

Dockerfile
docs/deployment/example/kubernetes/rc.yml
docs/deployment/example/kubernetes/svc.yml

Remove all requirement for users in container because you don't really need those and when running containers in not privileged mode(which openshift is running them as) then it says that it cannot update `/app/tmp` directory because we are not allowed to change files/directories which are owned by errbit user

[DOCKER] Remove requirement for having errbit user

---

.travis.yml
README.md

Also, cleanup MongoDB versions used for testing:
* Bump minor versions to be latest for each major release
* Remove MongoDB 3.2.x from testing, is EOL as of September 2018 
* Add MongoDB 4.0.0 to testing, just so we can gather experience
For the curious I've also added ruby-head to the build matrix, just so any issues can be seen and fixed.

CI: require ruby 2.5 passing

---

docs/configuration.md

Document initial admin user related env vars

---

app/controllers/health_controller.rb
spec/requests/health_controller_spec.rb

For more on why this pattern is problematic, read https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts and https://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/

Implement /health/readiness without using Timeout.timeout

---

config/application.rb

Class loading is not thread-safe, and using autoloading doesn't work reliably with a multithreaded puma server.
Fixes #1308

Rails: eager-load all of lib/

---

app/controllers/users/omniauth_callbacks_controller.rb
spec/controllers/users/omniauth_callbacks_controller_spec.rb

When using GITHUB_ORG_ID to automatically sign up new users, if the user has no email selected in his public profile, i.e, settings/profile looks like this:
Errbit won't receive any email and won't be able to create a new user, redirecting back to the sign in page without displaying any message.
This PR makes Errbit show a "Flash Error" message with the text: "You need to define and select a valid email in your Github profile"

GitHub Auth: Show error msg on empty email

---

app/models/notice.rb

Before this all CI runs failed when run on `ruby-head`

Fix specs on ruby 2.6.x

---

spec/spec_helper.rb

Warning this fixes:
```
/home/travis/build/errbit/errbit/spec/spec_helper.rb:13:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
```

Spec: Fix SimpleCov::Formatter::MultiFormatter warning

---

app/controllers/health_controller.rb

without this fix, when errbit upgraded mongoid from 5.0.2 to 5.4.0 (https://github.com/errbit/errbit/pull/1278), our mongo servers started seeing a new connection on every `readiness` request, and for some reason the connections were no longer closed implicitly (not sure how that was happening in 5.0.2). in our context, readiness is run every five seconds by kubernetes, so it was creating many connections pretty quickly, and this ultimately took down mongo servers on a few environments.

close mongo connection after creating

---

Gemfile
Gemfile.lock
spec/models/error_report_spec.rb
spec/spec_helper.rb

-1 dependency, wasn't pulling much weight.

Remove gem rspec-its dependency

---

app/assets/stylesheets/errbit.css.erb
app/controllers/problems_controller.rb
app/helpers/application_helper.rb
app/models/problem.rb
app/views/notices/_summary.html.haml
app/views/problems/_sparkline.html.haml
config/locales/en.yml
config/routes.rb
lib/sparklines.rb
spec/controllers/problems_controller_spec.rb
spec/lib/sparklines_spec.rb
spec/models/problem_spec.rb

This is mostly work from @danielbeardsley in https://github.com/errbit/errbit/pull/864. I made the sparklines queries happen in a separate ajax call so there is no chance it can slow down the rest of the problems page. I also updated rubocop stuff to hopefully fix the build. Maybe these changes make this ready for merge?

Sparklines with ajax and rubocop clean

---

README.md

Add note about the possibility of per-app notice grouping

---

.rubocop_todo.yml
app/controllers/problems_controller.rb
app/models/problem.rb
docs/apps.md
spec/models/problem_spec.rb

...to make problems page usable with noisy apps
this is the other half of #1273 , which i am declining since i did a rebase and added a bunch of commits that i didn't want somehow.

add /problems?exclude_apps=app1,app2 feature

---

lib/airbrake_api/v3/notice_parser.rb
spec/lib/airbrake_api/v3/notice_parser_spec.rb

My Airbrake config blacklists all keys: `config.blacklist_keys = [/.*/]` so `user_attributes` returns a String `"[Filtered]"` instead of a Hash. 
When trying to save this String to a `Notice` model, ErrBit throws:
Mongoid::Errors::InvalidValue: message: Value of type String cannot be written to a field of type Hash
[PROJECT_ROOT]/models/error_report.rb:65→ new
[PROJECT_ROOT]/models/error_report.rb:65→ make_notice
[PROJECT_ROOT]/models/error_report.rb:54→ generate_notice!
[PROJECT_ROOT]/controllers/api/v3/notices_controller.rb:24→ create
This PR ensures that `user_attributes` always returns a Hash.

Ensure user_attributes returns a Hash

---

app/controllers/health_controller.rb
spec/requests/health_controller_spec.rb

Warm up:
* Docker image boots with 116 MiB used.
* `ab -n 2000 -c 10 localhost:8080/health/liveness` raises memory usage up to 250 MiB.
* Running `ab` again does not change memory usage.
Before this PR:
* `ab -n 2000 -c 10 localhost:8080/health/readiness` raises memory usage up to 370 MiB.
* Further runs result in memory usage of 400 MiB, 480 MiB, 600 MiB.
After this PR:
* `ab -n 2000 -c 10 localhost:8080/health/readiness` raises memory usage up to 261 MiB.
* Running `ab` again does not change memory usage.

Fix memory leak in readiness health check endpoint

---

app/models/error_report.rb
spec/models/error_report_spec.rb
spec/models/notice_observer_spec.rb

A bit of history:
* #265 introduced a fix which zeroed out the notice count on a problem when it was resolved. This was done to cause notifications to re-trigger when if it were unresolved when recording a notice.
* This behaviour was changed in 13c8b21f91c07e7970029e87fbc6997bcf1e16a6 to instead reset on unresolve to preserve the notice count on resolved problems.
* This behaviour seems to have been lost in f646cf500aef1d37aeb28a4a11f5bf2a4930837c which reduces the number of queries when recording a notice.
This PR restores the desired resending on unresolving behaviour without requiring the notice count to be changed. This is done by checking if the existing problem is resolved before updating it (unresolving and incrementing notice count) and if so, always triggering notifications.

Resend notifications when generating notices on resolved problems

---

app/models/notice.rb
spec/models/notice_spec.rb

#1233 includes a test case with a long message that blows up mongo. one of the messages that was blowing up our mongo instance could be fixed with a truncation threshold of 995, but it feels better to fix more cases. this will affect all new messages with sizes between 964 and 1000, but doesn't really feel like it will break much. and it feels a lot better to store the notice and index *something* rather than blowing up. i wish i understood the details of what was going on here a bit better. i tried calling message.bytes.size on the test case message, but the number that came out didn't match exactly up with the number in the exception that was raised (it was closer than message.size, though):
````
message.size: 1000
message.bytes.size: 1047
Failures:
1) Notice#message= truncates the long …
```

fix #1233. this just uses the number that makes the test case pass

---

app.json

Before this change the postdeploy script was failing due to the :test
dependencies not being installed during the app deployment.
The default value for `$BUNDLE_WITHOUT` is `development:test`.
Fixes #1362.

Include test dependencies in the `bundle install`.

---

app/assets/javascripts/errbit.js
app/views/problems/search.js.haml

The issue is related to the fact that the `#problem_table` is emptied
when the search is run, and a new table is inserted in its place with
the result of the search. The existing click binding of the buttons 
at the end ofthe table (merge/delete/etc) is removed when 
the table is removed.
As a fix, `assets/javascripts/errbit.js` introduces global
`bindProblemButtonsActions` function which is extracted from the
body of `errbit.js`, containing handler of for problem buttons click
event. This function is then added to the result of
`views/problems/search.js.haml` to be run on a new problems table
when the search is returned.
Tried to create a rspec test for this, but had problems getting nokogiri 
to compile. Maybe it's time for Rails 6 update? 😅

#1385: Can't merge errors after search

---

README.md

Removed the non-existing *flippa/errbit-php* and replaced it with a working link to *wasilak/errbit-php*, as per [#1442](https://github.com/errbit/errbit/issues/1442)

Documentation: update reference to PHP client

---

app/controllers/problems_controller.rb
config/routes.rb
spec/controllers/problems_controller_spec.rb

you do not need an app id, strictly speaking, to find a problem, and if your metrics system does not happen to know the app id, but does know the problem id, it can be handy to have a way to link in to errbit.
hopefully this is small and uncontroversial enough to merge fast, but don't be afraid to merge my other--more controversial--branches too, which we've been running with for many months in production. ;)
thanks for this awesome project and let us know how we can help!

allow showing problem by id

---

app/assets/javascripts/errbit.js

Binding the click event on document with a selector keeps the functionality working after replacing the error details DOM (i.e. ajax older/newer links). Alternatively we could add the listener on the span after each replacement but I personally don't see a reason to overcomplicate it that way.
Fixes #1462

Fixes #1462 - backtrace does not expand after ajax pagination

---

app/models/comment.rb
app/views/problems/show.html.haml

This should fix the bug we're seeing where comments are being rendered
in a scrambled order.
This follows the `ordered` scope pattern from notices and problems:
https://github.com/errbit/errbit/blob/9f53eaaa0ee966ea2d8015e8eeacf6dde1709601/app/models/problem.rb#L62
https://github.com/errbit/errbit/blob/9f53eaaa0ee966ea2d8015e8eeacf6dde1709601/app/models/notice.rb#L36
Closes: https://github.com/errbit/errbit/issues/1483
CC @stevecrozz

Order comments in problem views by created_at

---

Gemfile.lock

Nokogiri v1.11.0 was released on 2021-01-03, which contains a fix for CVE-2020-26247, fully described at https://github.com/advisories/GHSA-vr8q-g5c7-m54m. That security advisory is reproduced here for your convenience.
**Severity**
Nokogiri maintainers have evaluated this as Low Severity (CVSS3 2.6).
**Description**
In Nokogiri versions <= 1.11.0.rc3, XML Schemas parsed by Nokogiri::XML::Schema are trusted by default, allowing external resources to be accessed over the network, potentially enabling XXE or SSRF attacks.
This behavior is counter to the security policy followed by Nokogiri maintainers, which is to treat all input as untrusted by default whenever possible.
Please note that this security fix was pushed into a new minor version, 1.11.x, rather than a patch release to the …

Update Nokogiri: v1.10.9 -> v1.11.0 to fix CVE-2020-26247

---

README.md

A new phone home feature in Airbrake introduced here: https://github.com/airbrake/airbrake-js/commit/78387b647b7fa2cd89b738171a1999ac29c989eb
This request will fail, I assume because with Errbit you self-host and do not have any project info at Airbrake backend.

disable remote config

---

Gemfile.lock

Mimemagic has [yanked all versions previous to version 0.3.7](https://rubygems.org/gems/mimemagic/versions). Since the Gemfile.lock included version 0.3.2, running `bundle install` failed.
See also:
* [Dependency on mimemagic 0.3.x no longer valid](https://github.com/rails/rails/issues/41750)

Bump mimemagic to version 0.3.9

---

app/models/backtrace.rb
spec/decorators/backtrace_line_decorator_spec.rb

I suppose there is a reason why the regex for the gem path wasn't anchored? I didn't change it.
I did remove unnecessary escapes of slashes which are not needed when using `%r` and it was used both escaped and not escaped before. Apart from that it just allows either `[PROJECT_ROOT]` and `/PROJECT_ROOT/` (GEM_ROOT respectively). 
Fixes #1477

Handle old and new backtrace format, fixes #1477

---

docs/deployment/docker.md

The path to the configuration file in "docker.md" has been fixed. The actual leads to the page with 404 error. Also added "bundle exec" statement before each rake command. Without it, there is an error related with the wrong version of rake.

Update docker documentation

---

.travis.yml
Gemfile
Gemfile.lock

Please don't merge yet.
Replacing therubyracer (dead since 2017) with [mini_racer](https://github.com/rubyjs/mini_racer) allows the ancient version of libv8 to get an update from 3.16 to 8.4 which fixes build errors on current systems (#1492 #1494).
As I understand it this is caused by a [bug in libv8](https://github.com/rubyjs/libv8/issues/310) and by a change in bundler which had [unintended side effects](https://github.com/rubygems/rubygems/pull/4127). With how this PR is right now this will cause bundler 2.2 to fail with an error as described in the v8 bug.
As I understand the linked bundler PR should make it so that a lock generated with <2.2 should fallback to old behaviour but I fail to understand what that effectively means as it still fails.
Anyway, for bundler 2.2 we would now …

[WiP] Replace therubyracer with mini_racer (updates v8)

---

app/interactors/outdated_problem_clearer.rb
app/interactors/resolved_problem_clearer.rb
spec/interactors/outdated_problem_clearer_spec.rb
spec/interactors/resolved_problem_clearer_spec.rb

when I was trying to run `bundle exec rake errbit:clear_outdated` I've got following error:
```
rake aborted!
Mongo::Error::OperationFailure: This command has been removed. If you would like to compact your data, use the 'compact' command. If you would like to rebuild indexes, use the 'reIndex' command. If you need to recover data, please see the documentation for repairing your database offline: http://dochub.mongodb.org/core/repair (59) (on consul.qtravel.ai)
```
This PR fixes it.

Change deprecated mongodb repairDatabase command to compact

---

.circleci/config.yml

Hi, maintainers.
Thank you for publishing a wonderful product on OSS. I used to use other products for a while, but I'm back. When I came back, I noticed that some of the errbit were out of date.
There are a few things to worry about, but [travis-ci.org](https://travis-ci.org), which is used for CI, ended on June 15, 2021 and announced the transition to [travis-ci.com](https://travis-ci.com), but travis-ci.com is credit-based, I thought it would be difficult to use with OSS, so this time I added a setting to run CI with CircleCI. If you prefer [GitHub Actions](https://github.com/features/actions), I would like to add a CI setting in GitHub Actions.
https://circleci.com
If you want CircleCI to work with your errbit organization, someone with errbit organization must create an account on …

👷 Add CircleCI config

---

.circleci/config.yml

Hi,
I deleted MongoDB v4.1 on CircleCI. (Because it seems that the version with an odd number of minor versions was out of the official surport. Refs: https://www.mongodb.com/support-policy/lifecycles)
I've already confirmed that the test passes with CircleCI.
Since v4.0 or later is still supported by the official status, I personally think that it is better to keep it supported as errbit. Because some users may have applications and DBs running as separate servers, instances or services. I leave the decision to the maintainers.
I'll continue to work on adding ruby 2.7 and updating the library.
Thank you.

🔥 Delete MongoDB v4.1 on CiecleCI

---

app/controllers/notices_controller.rb
app/controllers/problems_controller.rb
app/views/problems/show.html.haml
config/locales/en.yml
config/locales/pt-BR.yml
config/routes.rb
docs/notices.md
spec/controllers/notices_controller_spec.rb

Adds path /notice/:id, which takes you to the specific notice, unlike /locate/:id

allow for viewing a specific notice by id. w/ jasquat

---

app/views/notices/_atom_entry.atom.haml
spec/views/apps/show.atom.builder_spec.rb

Fixes error: NoMethodError: undefined method `number' for #<BSON::Document:0x00000005e11180> Did you mean? numeric?
Not sure, but my production app, as well as a fresh development snapshot does not displays atom feeds. The format of the Backtrace Lines seems to be changed.
This MR fixes that.

Fix: Atom feed backtrace error

---

README.md

Following the readme, I used the `airbrake` gem and followed the airbrake docs for configuration. I ran `gem install airbrake` and pointed airbrake to my errbit instance.
In the `development` Rails environment, this worked fine. In the `production` Rails environment, this yielded the following error:
```
E, [2022-03-25T10:10:04.695662 #1] ERROR -- : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access
Denied</Message><RequestId>WD57Y1AJCJ74WRKH</RequestId><HostId>W+P5KTtP4PAuz+U6mxLhJ5bbKzPuOPcvBRQTGezTtWb5oPtEyz8w+Z+WSedYdOYF3aif72tIcEY=</HostId></Error>
```
After quite a bit of searching and reading/patching airbrake code with @branch14, we saw that airbrake supports a feature called "[remote config](https://github.com/airbrake/airbrake-ruby/pull/636)", …

Document how to disable polling airbrake remote config

---

app.json

Based on the doc update that Errbit now requires Ruby 2.7 (https://github.com/errbit/errbit/commit/c4153cf19c1a7751777ea112fdcd01308bbbb484), update the Heroku config for the currently available Ruby 2.7 version on Heroku (https://devcenter.heroku.com/articles/ruby-support#ruby-versions).
As a side benefit, this allows using the current Heroku stack-20.

Configure Ruby 2.7 for Heroku

---

.github/workflows/publish.yml

Addresses #1512 
This PR adds a workflow definition file that will build and publish the image to dockerhub when you push a tagged version.
You can see a demo of how this worked on my fork:
```
git commit -m "Add publish GitHub action workflow"
git tag v9.9.0
git push --tags
```
Which triggered [this build](https://github.com/shreve/errbit/runs/5760542942), and pushed the image to [this Docker Hub repo](https://hub.docker.com/repository/docker/shreve/errbit/tags).
As you can see, it creates the layered semver tags: `9`, `9.9`, `9.9.0`, and the ever-useful `latest`.
The only configuration I needed to add was `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` in the repo actions secrets.

Add publish GitHub action workflow

---

.circleci/config.yml
Dockerfile
Gemfile
Gemfile.lock

This is PR update `mini_racer` gem to 0.6.2. Old version doesn't compile anymore on modern systems. Plus, related fixes.
1. Update `mini_racer` gem to 0.6.2. So, on modern systems (like macOS Monterey 12.4) project can be bundled. git clone + bundle == works!
2. Remove cache restore by key `rubygems-`. We should not restore cache from e.g. old ruby version.
3. Bump `CIRCLECI_RUBYGEMS_CACHE_KEY` to clear circle ci build cache.
4. Update rubygems (to 3.3.15) and bundler (to 2.3.15). In `Gemfile.lock` and in `Dockerfile`.
5. Replace `circleci/ruby` `-browsers-legacy` image with `cimg/ruby` and `-browsers`. `circleci/ruby` images was [deprecated](https://circleci.com/docs/2.0/next-gen-migration-guide/).

Update mini_racer gem to 0.6.2

---

.rspec
app/controllers/api/v1/stats_controller.rb
app/controllers/api/v3/notices_controller.rb
app/controllers/application_controller.rb
app/controllers/apps_controller.rb
app/controllers/notices_controller.rb
app/controllers/problems_controller.rb
app/controllers/users_controller.rb
app/models/app.rb
app/models/comment.rb
app/models/notice.rb
app/models/watcher.rb
config.ru

Hello,
This PR is prepare for Rails 5.0 migration. I already branch with port errbit to Rails 5.0, but don't tests it well. This is part of changes.
1. [RSpec automatically turn on or off colors](https://rspec.info/blog/2017/05/rspec-3-6-has-been-released/).
2. Don't compress response. Remove `Rack::Deflater`. If anyone really need, they should install and configure proxy for this. E.g. nginx.
3. Replace http status codes with names.
4. Change `protected` to `private`.

Prepare for rails 5.0

---

app/helpers/problems_helper.rb
app/views/problems/show.html.haml
spec/helpers/problems_helper_spec.rb

It always bothered me that pasting a URL into a comment wouldn't allow you to simply click it, instead you'd have to copy and paste it into your Search bar.

Format comments

---

app/helpers/hash_helper.rb
spec/helpers/hash_helper_spec.rb

We are experiencing errors in `Self.Errbit` when trying to open some Problems.
After some digging, I found out that `notice.params` returned a String, instead of a hash.

Handle strings in pretty_hash to prevent exceptions (NoMethodError: undefined method 'keys' for #<String>)

---

app/interactors/outdated_problem_clearer.rb

Atlas' M0 tier does not allow execution of COMPACT command. Running this rake exits with the following error and aborting the whole deletion process. However, it can be skipped if operation is not allowed and outdated problems are still destroyed.
```bash
~ $ ERRBIT_PROBLEM_DESTROY_AFTER_DAYS=21 rake errbit:clear_outdated Overwriting existing field _id in class App.
rake aborted!
Mongo::Error::OperationFailure: [8000:AtlasError]: CMD_NOT_ALLOWED: compact (on errbit-shard-00-01.pf7i2.mongodb.net:27017) /app/vendor/bundle/ruby/2.7.0/gems/mongo-2.18.1/lib/mongo/operation/result.rb:364:in `raise_operation_failure'
/app/vendor/bundle/ruby/2.7.0/gems/mongo-2.18.1/lib/mongo/operation/result.rb:330:in `validate!'
/app/vendor/bundle/ruby/2.7.0/gems/mongo-2.18.1/lib/mongo/operation/shared/response_h …
```

fix: Skip COMPACT via clear_outdated if not allowed

---

.github/dependabot.yml

This is first step to upgrade ruby and rails.
Dependabot will create around 30 PR's. So, it will be faster than I will update them one-by-one.

Enable Dependabot for bundler, github-actions and docker

---

Gemfile
Gemfile.lock

Soon or later, this will happen.
This PR replace: `actionmailer`, `actionpack` and `railties` with simple `rails` gem.

Replace actionmailer, actionpack and railties with rails

---

Dockerfile

We install hoptoad_notifier from git. Add `git` to Dcokerfile to fix build.

Add git to docker image

---

Gemfile.lock

[CVE-2025-27610](https://github.com/rack/rack/security/advisories/GHSA-7wqh-767x-r66v)

Update rack gem to 2.2.13

---

app/helpers/notices_helper.rb
app/helpers/sort_helper.rb

`UTF-8 has been the default source file encoding since Ruby 2.0.`
[Link](https://rubystyle.guide/#utf-8)

Rubocop: Style/Encoding

---

Gemfile.lock

Changes:
1. Update `faraday` gem to 2.12.2
2. Update `faraday-net_http` gem to 3.4.0
3. Update `jwt` gem to 2.10.1
4. Update `oauth2` gem to 2.0.9
5. Update `octokit` gem to 9.2.0
6. Update `omniauth-github` gem to 2.0.1
7. Update `omniauth-google-oauth2` gem to 1.2.1
8. Update `omniauth-oauth2` gem to 1.8.0
9. Update `sawyer` gem to 0.9.2

Upgrade faraday, oauth2 and omniauth gems

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/content_security_policy.rb
config/initializers/filter_parameter_logging.rb
config/initializers/new_framework_defaults_7_1.rb
config/initializers/permissions_policy.rb

Changes:
1. Ruby on Rails 7.1.5.1
NOTE: This deprecation will go away only after migration to Rails 7.2.
```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from <main> at /home/runner/work/errbit/errbit/config/environment.rb:21)
```

Rails 7.1.5.1

---

.github/workflows/jruby.yml
.github/workflows/rspec.yml
README.md
app/lib/errbit/version.rb
docs/upgrading.md

Changes:
1. Drop support for MongoDB 4.0, 4.2, 4.4 and 5.0
2. Bump version to 0.11.0-dev

Start 0.11.0 dev

---

app/jobs/destroy_problems_by_id_job.rb
spec/jobs/destroy_problems_by_id_job_spec.rb

Before:
```
rspec spec/jobs/destroy_problems_by_id_job_spec.rb --profile
Randomized with seed 62023
DestroyProblemsByIdJob
destroys all selected problems, even with a large amount of them
should work with a fresh new application
destroys all selected problems
Top 3 slowest examples (15.75 seconds, 100.0% of total time):
DestroyProblemsByIdJob destroys all selected problems, even with a large amount of them
15.57 seconds ./spec/jobs/destroy_problems_by_id_job_spec.rb:24
DestroyProblemsByIdJob should work with a fresh new application
0.10749 seconds ./spec/jobs/destroy_problems_by_id_job_spec.rb:38
DestroyProblemsByIdJob destroys all selected problems
0.07038 seconds ./spec/jobs/destroy_problems_by_id_job_spec.rb:16
Finished in 15.75 seconds (files took 1.93 seconds to load)
3 examples, 0 …
```

Speed up tests

---

docker-compose.yml

File `docker-compose.yml` is for development. We don't need Errbit itself in it.

Remove errbit from docker-compose.yml
