errbit/errbit

CHANGELOG.md
=> Update changelog to reflect latest master

db/migrate/20121005142110_regenerate_err_fingerprints.rb
Commit https://github.com/errbit/errbit/commit/da3946bef7921e5a6df0d55fc2f556b641884ada refactored fingerprinting into a Fingerprint module, updated the migration for that.
=> Fix fingerprinting migration as it is refactored

db/seeds.rb
This seems superior to the default password of `'password'`. Thoughts on this?
=> Update seed: random password during install

lib/airbrake_api/v3/notice_parser.rb, spec/fixtures/api_v3_request_without_backtrace.json, spec/lib/airbrake_api/v3/notice_parser_spec.rb
=> Fix parsing V3 api notice without backtrace

config/deploy.example.rb
I've changed a little bit the Unicorn part of the `deploy.example.rb` file.
I've tested it on a real setup.
=> Unicorn deploy tweaks

README.md
I followed the steps word for word and got errors because of mongodb not installed / running.  I just made a few simple notes in the README for the local install and updated to the shortcut version of starting a rails server.
=> adding readme changes for local install

Procfile, config/unicorn.default.rb
To use `PORT` env var when using foreman
=> respect PORT env var

config/mongo.rb
Proposed fix for https://github.com/errbit/errbit/issues/849
=> stop modifying custom mongo uri

app/models/notification_services/hipchat_service.rb
Hi guys!
Is there any reason why all errors are silent for HipChat?
=> Notify about errors in HipChat

Gemfile
=> hack around broken rvm ruby detection

app/models/notification_services/webhook_service.rb, spec/models/notification_service/webhook_service_spec.rb
This PR adds problem URL to webhook payload.
I guess that this is useful to integrate other system.
=> Add url to webhook service

Gemfile.lock, app/assets/javascripts/form.js, app/assets/stylesheets/application.css.erb, app/assets/stylesheets/errbit.css.erb, app/assets/stylesheets/issue_tracker_icons.css.erb, app/controllers/apps_controller.rb, app/controllers/problems_controller.rb, app/decorators/issue_tracker_decorator.rb, app/decorators/issue_tracker_type_decorator.rb, app/helpers/application_helper.rb, app/models/issue_tracker.rb, app/views/apps/_issue_tracker_fields.html.haml, app/views/apps/index.html.haml, app/views/problems/_issue_tracker_links.html.haml, config/initializers/assets.rb, lib/tasks/errbit/demo.rake, spec/controllers/problems_controller_spec.rb, spec/decorators/issue_tracker_decorator_spec.rb, spec/decorators/issue_tracker_type_decorator_spec.rb, spec/views/problems/show.html.haml_spec.rb
=> new image icon interface

docs/api/stats.md
Here's my attempt at documenting the method for representing error statistics.
Add new api docs in docs/api/stats.md
There are no docs for this API, and apparently it's not the same as the Airbrake API, so the only way to figure out how to use it is to read the source code.
Documentation will help us to understand how we can get error statistics on errbit. :smile_cat: 
https://github.com/errbit/errbit/issues/479
=> add docs for statistics API

app/models/notification_services/slack_service.rb, spec/models/notification_service/slack_service_spec.rb
This adds in attachment formatting for Slack
=> Adds in formatting for Slack

app/views/mailer/deploy_notification.html.haml, app/views/mailer/deploy_notification.text.erb
It's currently in the web UI but not included in the e-mail notifications.
=> Add deploy "message" to e-mail notifications

app/views/mailer/err_notification.html.haml, app/views/mailer/err_notification.text.erb
#870 App Server not in notification email
Added App Server into Notification Emails
=> #870 App Server not in notification email

app.json
https://github.com/errbit/errbit/pull/888 works perfectly, thx @3zcurdia. though, i would recommend enforcing ssl by defaul.
=> heroku button: enforce ssl by default

README.md
=> Fix wrong markup in README.md

app/models/notification_services/gtalk_service.rb
=> Wrap jabber notifications in a timeout block

app/models/user.rb, spec/models/user_spec.rb
Reference #981 
I don't know if it's the best approach. What do you think?
=> Disable user validation when reset password

Gemfile.lock
CVE-less unclosed comment uninitialized access issue
CVE-2015-1819
CVE-2015-7941_1
CVE-2015-7941_2
CVE-2015-7942
CVE-2015-7942-2
CVE-2015-8035
CVE-2015-7995
=> Update Nokogiri to address multiple CVEs

Gemfile.lock
https://gemnasium.com/errbit/errbit
=> Update gem uglifier in order to avoid security vuln as reported by gemnasium

config/environment.rb, docs/configuration.md
@stevecrozz this adds the syslog functionality but something seems wrong since some output is still replicated in STDOUT. You may want to take a look.
=> Add syslog functionality

Gemfile, Gemfile.lock
This update should fix #994 as mentioned in [this comment](https://github.com/errbit/errbit/issues/994#issuecomment-157064172)
=> Update mongoid gem to 5.0.2

CHECKS, Gemfile, config/boot.rb, docs/deployment.md, docs/deployment/dokku.md
I have successfully deployed errbit to dokku and [here's the output](https://gist.github.com/ebeigarts/8c3687eddd62b339fe05).
There was an [issue](https://github.com/dokku/dokku/issues/1899) with the min ruby check, so I moved it to config/boot.rb.
=> Dokku deployment support

app/assets/stylesheets/errbit.css.erb, app/views/problems/_issue_tracker_links.html.haml
Also added a missing span, and used the create image for the unlink image.  Also placed images inside the link.
=> closes #1047 tracker icon buttons

README.md
Fix the existing mistakes and typo:bow: related on omniauth.
=> [docs] Fix callback url of github and google

config/load.rb, docs/configuration.md
=> adding MONGODB_URI to support recent heroku change

app/controllers/problems_controller.rb, app/views/apps/_fields.html.haml, app/views/devise/sessions/new.html.haml, app/views/kaminari/notices/_paginator.html.haml, app/views/notices/_summary.html.haml, app/views/problems/_table.html.haml, app/views/problems/index.html.haml, app/views/problems/show.html.haml, app/views/site_config/index.html.haml, app/views/users/_fields.html.haml, app/views/users/edit.html.haml, app/views/users/index.html.haml, app/views/users/new.html.haml, app/views/users/show.html.haml, config/locales/devise.pt-BR.yml, config/locales/en.yml, config/locales/pt-BR.yml, config/locales/rails.pt-BR.yml
The current internationalization keys weren't enough to allow a full translation of Errbit. I added all the missing keys and their corresponding pt-BR translation. The rails.pt-BR.yml was introduced to translate "time in words" functions. All tests passed with success.
=> more I18n and pt-BR translations

lib/airbrake_api/v3/notice_parser.rb, spec/lib/airbrake_api/v3/notice_parser_spec.rb
=> prevent NoMethodError for optional environment field

app/decorators/backtrace_decorator.rb, spec/decorators/backtrace_decorator_spec.rb
=> prevent NoMethodError for optional backtrace list

config/deploy.example.rb, config/locales/en.yml
Just a small grammar fix - when used as a verb, 'set up' is two words.
http://www.future-perfect.co.uk/grammar-tip/is-it-setup-set-up-or-set-up/
http://www.merriam-webster.com/dictionary/setup
=> Update grammar ('setup' to 'set up')

.travis.yml, app.json, docs/deployment/dokku.md, docs/deployment/heroku.md
It seems a stable release of Ruby 2.3.x.
=> Use Ruby 2.3.3 by default

Dockerfile, Gemfile
Merge request is ready for review
Changes:
- Optimise `bundle install`
- Creates a non-root user to run application
- Use Virtual Packages feature of Alpine to reduce image size
- Add `HEALTHCHECK`
=> Improve Dockerfile

.rubocop_todo.yml, Dockerfile, app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, config/initializers/devise.rb, config/load.rb, config/locales/en.yml, db/seeds.rb, docs/configuration.md, spec/acceptance/acceptance_helper.rb, spec/acceptance/sign_in_with_google_spec.rb, spec/controllers/users/omniauth_callbacks_controller_spec.rb
* Add ARG variables to allow for UID/GID mapping
* Update MAINTAINER (deprecated) instruction to LABEL
* Improve HEALTHCHECK, now curls the default IP of the container
* Add GOOGLE_AUTO_PROVISION config option to toggle automatic account creation
* Add GOOGLE_REDIRECT_URI config option to set a custom redirect location. This is useful if errbit is being served behind a reverse proxy that's terminating TLS
* Add GOOGLE_AUTHORIZED_DOMAINS config option to whitelist trusted domains for login
* Allow for custom user during database seed
=> Improve Google Auth

app/controllers/api/v3/notices_controller.rb, app/controllers/comments_controller.rb, app/controllers/problems_controller.rb, app/helpers/sort_helper.rb, app/models/notification_services/webhook_service.rb, config/initializers/ssl_enforcer.rb, lib/airbrake_api/v3/notice_parser.rb, lib/hoptoad/v2.rb
Replaced ruby and rails idioms for faster code.  https://github.com/JuanitoFatas/fast-ruby
=> Speed up common idioms

.travis.yml, Gemfile, Gemfile.lock
Setup from https://docs.travis-ci.com/user/database-setup/#MongoDB
=> Travis CI: use specific mongodb database versions

app/decorators/backtrace_line_decorator.rb, spec/decorators/backtrace_line_decorator_spec.rb
Thanks to @badmanski for the original fix. This PR includes that fix along with some tests to demonstrate it works.
Refs #1185 and #1135
=> Fix nil reference in BacktraceLineDecorator

.travis.yml, Dockerfile, Gemfile, Gemfile.lock, app/views/devise/sessions/new.html.haml, app/views/shared/_link_github_account.html.haml, app/views/shared/_link_google_account.html.haml, config/initializers/devise.rb, config/locales/devise.en.yml, spec/spec_helper.rb
This builds on the changes in #1249
=> Upgrade devise to support ruby 2.5

app/controllers/health_controller.rb, docs/deployment.md, spec/requests/health_controller_spec.rb
The kubernetes probe system wants non-200's on failures.
=> kubernetes health checks should return 500 on failure. w/ burnettk

app.json
Forever-credentials to Heroku review apps, see `app.json`:
* User: `admin@example.com`
* Pass: `demo-admin`
=> Heroku review app: use a fixed admin email/password for easier review

Gemfile, Gemfile.lock
This will allow depfu to save the day  with keeping everything up to date, I'm sure.
=> Gemfile: allow test gems to be upgraded as appropriate

app/views/users/edit.html.haml
=> user#edit: remove duplicate error output

app.json, db/seeds.rb, docs/configuration.md
Status: user/password is now set correctly. No demo data yet.
=> Heroku deploy: add demo data too

docker-compose.yml
update docker compose to v3
- substitute links -> depends_on
- nest containers under services
- update mongo to last minor -> 4.1
=> Update docker-compose.yml & upgrade mongo to 4.1

.teatro.yml
I propose to delete this config because the http://teatro.io service doesn't work anymore
=> remove unused .teatro.yml

app/views/problems/show.html.haml
=> Remove extra :

docs/deployment/heroku.md
Thank you for updating the MongoDB Atlas migration documentation. It has been very helpful in migrating from mLab. I made a PR of a small mistake I noticed during the migration. You can merge them if you'd like.
=> Update Heroku documentation

app/views/notices/_user_attributes.html.haml
=> Escape user attribute value before passing it to Rinku

app/decorators/problem_decorator.rb, app/views/problems/_table.html.haml
=> Show error class in problem table if there is no message

app/controllers/api/v1/comments_controller.rb, config/routes.rb, spec/controllers/api/v1/comments_controller_spec.rb
We use errbit at work every day and, as of today, automated some processes. Tho, we've noticed, that you are unable to commend via the API. So I've implemented a basic API to be able to create and list all commend of a problem.
Feedback is welcome ;)
=> Add comments api v1

LICENSE, README.md
=> Replace Circle CI link with GitHub Action

Gemfile, Gemfile.lock
Remove gems:
1. `better_errors`
2. `binding_of_caller`
3. `meta_request`
=> Remove better_errors,  binding_of_caller, and meta_request gems

.github/workflows/rspec.yml
This PR fixes Dependabot `ffi` gem update
=> Fix rubygems and bundler versions for GitHub Actions

.github/dependabot.yml, .github/workflows/actionlint.yml, CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/problems_controller.rb, package.json, spec/models/error_report_spec.rb
Changes:
1. Add GitHub Action for `actionlint`
2. Explicitly add `uri` gem
3. Add js package `prettier` for linting and reformatting css files. We don't plan use any of js packages from nodejs in production.
4. Dependabot: add npm package ecosystem
=> General fixes

CONTRIBUTING.md, README.md, RELEASE.md, app/controllers/api/v3/notices_controller.rb, app/decorators/backtrace_line_decorator.rb, app/helpers/problems_helper.rb, app/models/site_config.rb, app/views/apps/_configuration_instructions.html.erb, app/views/apps/_fields.html.haml, app/views/layouts/application.html.haml, docs/DEVELOPER-ADVANCED.md, docs/api/stats.md, docs/apps.md, docs/configuration.md, docs/deployment.md, docs/deployment/docker.md, docs/deployment/dokku.md, docs/deployment/heroku.md, docs/deployment/kubernetes.md, docs/upgrading.md, spec/controllers/users/omniauth_callbacks_controller_spec.rb
Changes:
1. Remove outdated bagdes for codeclimate and coveralls.
2. Fix typos
3. Documentation updates
4. Update branch placeholder from `main` to `e.g. main`
5. Remove link to systemd unit files (they are outdated and use unicorn)
=> Documentation updates

config/initializers/devise.rb
Change bcrypt cost from 11 to 12.
=> Devise: improve security

Gemfile, Gemfile.lock, app/helpers/problems_helper.rb, spec/helpers/problems_helper_spec.rb, spec/mailers/mailer_spec.rb
Changes:
1. Remove `spec-pending_for` gem
2. Adjust tests
=> Remove rspec-pending_for gem

app/interactors/resolved_problem_clearer.rb
Fix from #1552 fix only one place.
This PR adds this fix to second case.
=> One more fix for issue #1551

.editorconfig, Gemfile, Gemfile.lock, docs/configuration.md, docs/rack-timeout.md
Changes:
1. Add `rack-timeout` gem
2. Add and update docs
3. Add `.editorconfig`
Closes #1927
=> Add rack-timeout gem
